#pragma once

#include "server-splice.h"

#include <nlohmann/json.hpp>

#include <cstddef>
#include <cstring>
#include <string>
#include <stdexcept>

// Only generated bytes enter this scanner. Prompt copies of commands are inert.
struct server_thought_scanner {
    static constexpr size_t max_payload = 16384;
    static constexpr size_t max_escaped_payload = 32768;

    bool thinking = false;
    bool line_start = true;
    server_splice_scanner lines;
    bool sending = false;
    bool oversized = false;
    size_t escaped_payload_size = 0;
    std::string pending;
    std::string payload;
    std::string command;
    std::string error;

    std::string continuation() const {
        if (!thinking || !command.empty()) {
            return {};
        }
        // An oversized body can end at a partial UTF-8 byte. Only its eventual error matters.
        return sending ? "<ct:send>" + (oversized ? std::string(max_payload + 1, ' ') : payload) + pending : pending;
    }

    nlohmann::json continuation_state() const {
        // A partial command can only have started outside a fence at column zero.
        const bool replay = sending || !pending.empty();
        const auto position = replay ? server_splice_scanner{} : lines;
        return {
            {"line_start", replay || line_start},
            {"fence", position.fence ? std::string(1, position.fence) : std::string()},
            {"fence_size", position.fence_size},
            {"line_marker", position.line_marker ? std::string(1, position.line_marker) : std::string()},
            {"line_marker_size", position.line_marker_size},
            {"line_indent", position.line_indent},
            {"line_marker_possible", position.line_marker_possible},
            {"line_marker_done", position.line_marker_done},
            {"line_marker_tail_space", position.line_marker_tail_space},
            {"line_backtick_info", position.line_backtick_info},
        };
    }

    void restore_state(const nlohmann::json & state) {
        if (!state.is_object()) {
            throw std::invalid_argument("thought_state must be an object");
        }
        auto position = server_splice_scanner{};
        bool start = true;
        for (const auto & field : state.items()) {
            const auto & key = field.key();
            const auto & value = field.value();
            if (key == "fence" || key == "line_marker") {
                if (!value.is_string() || (value != "" && value != "`" && value != "~")) {
                    throw std::invalid_argument("thought_state fence markers must be empty, backtick or tilde");
                }
                const auto marker = value.get<std::string>();
                (key == "fence" ? position.fence : position.line_marker) = marker.empty() ? 0 : marker.front();
            } else if (key == "fence_size" || key == "line_marker_size" || key == "line_indent") {
                if (!value.is_number_integer() || value.get<int64_t>() < 0 || value.get<uint64_t>() > 0x7fffffff) {
                    throw std::invalid_argument("thought_state marker lengths must be bounded nonnegative integers");
                }
                const auto size = value.get<size_t>();
                if (key == "fence_size") { position.fence_size = size; }
                else if (key == "line_marker_size") { position.line_marker_size = size; }
                else if (size <= 3) { position.line_indent = static_cast<unsigned>(size); }
                else { throw std::invalid_argument("thought_state line_indent must be at most three"); }
            } else {
                if (!value.is_boolean()) {
                    throw std::invalid_argument("thought_state flags must be boolean");
                }
                const bool flag = value.get<bool>();
                if (key == "line_start") { start = flag; }
                else if (key == "line_marker_possible") { position.line_marker_possible = flag; }
                else if (key == "line_marker_done") { position.line_marker_done = flag; }
                else if (key == "line_marker_tail_space") { position.line_marker_tail_space = flag; }
                else if (key == "line_backtick_info") { position.line_backtick_info = flag; }
                else { throw std::invalid_argument("unknown thought_state field: " + key); }
            }
        }
        if ((position.fence == 0) != (position.fence_size == 0) ||
                (position.fence && position.fence_size < 3) ||
                (position.line_marker == 0) != (position.line_marker_size == 0)) {
            throw std::invalid_argument("thought_state marker and length disagree");
        }
        if (start && (position.line_marker || position.line_indent || !position.line_marker_possible ||
                position.line_marker_done || !position.line_marker_tail_space || position.line_backtick_info)) {
            throw std::invalid_argument("thought_state line start has nonempty line state");
        }
        lines = position;
        line_start = start;
    }

    void feed(const std::string & piece) {
        if (!thinking || !command.empty()) {
            return;
        }
        for (char c : piece) {
            pending += c;
            while (!pending.empty()) {
                bool prefix = false;
                const char * matched = nullptr;
                for (const char * marker : {"<ct:peek/>", "<ct:inbox/>", "<ct:send>", "</ct:send>"}) {
                    if ((!sending && (!line_start || lines.fence)) ||
                            sending != (std::strcmp(marker, "</ct:send>") == 0)) {
                        continue;
                    }
                    if (std::strncmp(marker, pending.c_str(), pending.size()) == 0) {
                        prefix = true;
                        if (std::strlen(marker) == pending.size()) {
                            matched = marker;
                            break;
                        }
                    }
                }
                if (matched) {
                    pending.clear();
                    line_start = false;
                    if (std::strcmp(matched, "<ct:send>") == 0) {
                        sending = true;
                    } else {
                        command = std::strcmp(matched, "<ct:peek/>") == 0 ? "peek" :
                                  std::strcmp(matched, "<ct:inbox/>") == 0 ? "inbox" : "send";
                        if (oversized) {
                            payload.clear();
                            error = "thought message exceeds 16384 text bytes or 32768 JSON bytes";
                        }
                        return;
                    }
                } else if (prefix) {
                    break;
                } else {
                    if (sending) {
                        const auto byte = static_cast<unsigned char>(pending.front());
                        const size_t escaped_size = byte == '"' || byte == '\\' ? 2 :
                            byte == '\b' || byte == '\f' || byte == '\n' || byte == '\r' || byte == '\t' ? 2 :
                            byte < 0x20 ? 6 : 1;
                        if (payload.size() < max_payload && escaped_payload_size + escaped_size <= max_escaped_payload) {
                            payload += pending.front();
                            escaped_payload_size += escaped_size;
                        } else {
                            oversized = true;
                        }
                    } else {
                        const char byte = pending.front();
                        lines.feed(std::string(1, byte == '\r' ? '\n' : byte));
                        line_start = byte == '\r' || byte == '\n';
                    }
                    pending.erase(0, 1);
                }
            }
        }
    }
};
