#pragma once

#include <cstddef>
#include <cstring>
#include <string>

// Only generated bytes enter this scanner. Prompt copies of commands are inert.
struct server_thought_scanner {
    static constexpr size_t max_payload = 16384;
    static constexpr size_t max_escaped_payload = 32768;

    bool thinking = false;
    bool sending = false;
    bool oversized = false;
    size_t escaped_payload_size = 0;
    std::string pending;
    std::string payload;
    std::string command;
    std::string error;

    std::string continuation() const {
        if (!thinking || !command.empty()) {
            return {};
        }
        // An oversized body can end at a partial UTF-8 byte. Only its eventual error matters.
        return sending ? "<ct:send>" + (oversized ? std::string(max_payload + 1, ' ') : payload) + pending : pending;
    }

    void feed(const std::string & piece) {
        if (!thinking || !command.empty()) {
            return;
        }
        for (char c : piece) {
            pending += c;
            while (!pending.empty()) {
                bool prefix = false;
                const char * matched = nullptr;
                for (const char * marker : {"<ct:peek/>", "<ct:inbox/>", "<ct:send>", "</ct:send>"}) {
                    if (sending != (std::strcmp(marker, "</ct:send>") == 0)) {
                        continue;
                    }
                    if (std::strncmp(marker, pending.c_str(), pending.size()) == 0) {
                        prefix = true;
                        if (std::strlen(marker) == pending.size()) {
                            matched = marker;
                            break;
                        }
                    }
                }
                if (matched) {
                    pending.clear();
                    if (std::strcmp(matched, "<ct:send>") == 0) {
                        sending = true;
                    } else {
                        command = std::strcmp(matched, "<ct:peek/>") == 0 ? "peek" :
                                  std::strcmp(matched, "<ct:inbox/>") == 0 ? "inbox" : "send";
                        if (oversized) {
                            payload.clear();
                            error = "thought message exceeds 16384 text bytes or 32768 JSON bytes";
                        }
                        return;
                    }
                } else if (prefix) {
                    break;
                } else {
                    if (sending) {
                        const auto byte = static_cast<unsigned char>(pending.front());
                        const size_t escaped_size = byte == '"' || byte == '\\' ? 2 :
                            byte == '\b' || byte == '\f' || byte == '\n' || byte == '\r' || byte == '\t' ? 2 :
                            byte < 0x20 ? 6 : 1;
                        if (payload.size() < max_payload && escaped_payload_size + escaped_size <= max_escaped_payload) {
                            payload += pending.front();
                            escaped_payload_size += escaped_size;
                        } else {
                            oversized = true;
                        }
                    }
                    pending.erase(0, 1);
                }
            }
        }
    }
};
