import { build } from 'esbuild';
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { resolve, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const result = await build({
    entryPoints: [join(root, 'app.js')], bundle: true, minify: true,
    format: 'iife', target: ['es2022'], write: false, metafile: true,
    legalComments: 'inline', tsconfigRaw: {},
    nodePaths: [join(root, 'node_modules')],
    alias: { '$lib/constants': join(root, 'upstream-constants.ts') }
});
let css = await readFile(join(root, 'node_modules/katex/dist/katex.min.css'), 'utf8');
// Modern browsers use WOFF2. Embed it once; drop duplicate WOFF/TTF fallbacks.
css = css.replace(/src:([^;}]+);/g, (_, sources) => {
    const woff = sources.match(/url\(([^)]+\.woff2)\) format\(["']?woff2["']?\)/);
    return woff ? 'src:url(' + woff[1] + ') format("woff2");' : 'src:' + sources + ';';
});
const urls = [...new Set([...css.matchAll(/url\(([^)]+)\)/g)].map(match => match[1]))];
for (const url of urls) {
    const bytes = await readFile(join(root, 'node_modules/katex/dist', url));
    css = css.split('url(' + url + ')').join('url(data:font/woff2;base64,' + bytes.toString('base64') + ')');
}
css += '\n' + await readFile(join(root, 'node_modules/highlight.js/styles/github-dark.min.css'), 'utf8');
css += '\n' + await readFile(join(root, 'style.css'), 'utf8');
const script = result.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
let html = await readFile(join(root, 'index.html'), 'utf8');
html = html.replace('/* STYLE */', () => css).replace('/* SCRIPT */', () => script);
if (html.includes(')cthtml"')) throw new Error('Raw-string delimiter collision');
await writeFile(join(root, 'crossthink-ui.generated.h'),
    '// Generated by npm run build in tools/crossthink/ui. Do not edit.\n' +
    '// Third-party notices: THIRD_PARTY_LICENSES.txt\n#pragma once\n' +
    'static constexpr char crossthink_ui[] = R"cthtml(' + html + ')cthtml";\n');
await writeFile(join(root, 'dist.html'), html);

// Preserve every bundled package's license, including transitive dependencies.
const packages = new Map();
for (const input of Object.keys(result.metafile.inputs)) {
    let directory = dirname(resolve(input));
    while (directory.includes('node_modules')) {
        try {
            const pkg = JSON.parse(await readFile(join(directory, 'package.json'), 'utf8'));
            if (pkg.name && pkg.version) { packages.set(directory, pkg); break; }
        } catch (_) {}
        directory = dirname(directory);
    }
}
for (const name of ['katex', 'highlight.js']) {
    const directory = join(root, 'node_modules', name);
    packages.set(directory, JSON.parse(await readFile(join(directory, 'package.json'), 'utf8')));
}
let notices = 'Third-party packages embedded in the crossthink browser UI.\n' +
    'Generated from package-lock.json and the esbuild dependency graph.\n';
for (const [directory, pkg] of [...packages].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
    notices += '\n\n' + '='.repeat(72) + '\n' + pkg.name + ' ' + pkg.version + '\nLicense: ' +
        (typeof pkg.license === 'string' ? pkg.license : JSON.stringify(pkg.license)) + '\n';
    const files = (await readdir(directory)).filter(name => /^(license|licence|copying|notice)([.-]|$)/i.test(name)).sort();
    if (!files.length) {
        if (['remark-math', 'rehype-katex'].includes(pkg.name)) {
            notices += '\\n' + await readFile(join(root, 'licenses/remark-math.txt'), 'utf8');
        } else {
            throw new Error('Missing license file for bundled package ' + pkg.name);
        }
    }
    for (const file of files) notices += '\n' + file + '\n' + await readFile(join(directory, file), 'utf8');
}
await writeFile(join(root, 'THIRD_PARTY_LICENSES.txt'), notices);
console.log('Embedded UI: ' + html.length.toLocaleString() + ' bytes; ' + packages.size + ' package notices.');
